# Generated by Django 3.1.5 on 2021-02-01 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="movie", old_name="title", new_name="Title",),
        migrations.RenameField(model_name="movie", old_name="type", new_name="Type",),
        migrations.RenameField(model_name="movie", old_name="year", new_name="Year",),
    ]
