# Generated by Django 3.1.5 on 2021-02-02 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MainApp", "0002_auto_20210201_1501"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie", old_name="imbdId", new_name="imdbID",
        ),
    ]
